swagger: "2.0"
info:
  description: "This is an API documentation for the QUIZY API server."
  version: 1.0.0
  title: Quizy API Documentation
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: 
  - stocka-demo.herokuapp.com
tags:
  - name: test
    description: Operations on testing the application
  - name: user
    description: Operations on users
  - name: account
    description: Operations on user account
  - name: stock
    description: Operations on stocks
schemes:
  - https
paths:
  /:
    get:
      tags:
        - test
      summary: Test server connection
      description: Test the server connection
      operationId: testServer
      consumes:
        - application/json
        - application/x-www-form-urlencoded
      produces:
        - application/json
      responses:
        "200":
          description: Welcome to Stocka application with nodejs and mongodb!
  /api/v1:
    get:
      tags:
        - test
      summary: Test api connection
      description: Test the api connection
      operationId: testAPI
      consumes:
        - application/json
        - application/x-www-form-urlencoded
      produces:
        - application/json
      responses:
        "200":
          description: Welcome to the Stocka API v1.0! 
  /api/v1/auth:
    get:
      tags:
        - test
      summary: Test auth API
      description: Test the auth service connection
      operationId: testAuth
      consumes:
        - application/json
        - application/x-www-form-urlencoded
      produces:
        - application/json
      responses:
        "200":
          description: Welcome to the Stocka API v1.0! This is auth routes
  /api/v1/stocks:
    get:
      tags:
        - test
      summary: Test stock API
      description: Test the stock service connection
      operationId: testStock
      consumes:
        - application/json
        - application/x-www-form-urlencoded
      produces:
        - application/json
      responses:
        "200":
          description: Welcome to the Stocka API v1.0! This is stock routes
  /api/v1/profile/test:
    get:
      tags:
        - test
      summary: Test profile API
      description: Test the profile service connection
      operationId: testProfile
      consumes:
        - application/json
        - application/x-www-form-urlencoded
      produces:
        - application/json
      responses:
        "200":
          description: Welcome to the Stocka API v1.0! This is profile routes
  /api/v1/accounts/test:
    get:
      tags:
        - test
      summary: Test accounts API
      description: Test the account service connection
      operationId: testAccount
      consumes:
        - application/json
        - application/x-www-form-urlencoded
      produces:
        - application/json
      responses:
        "200":
          description: Welcome to the Stocka API v1.0! This is account routes
  "/api/v1/auth/login":
    post:
      tags:
        - user
      summary: Authenticates user
      description: "Allows user into the application if registered"
      operationId: userLogin
      consumes:
        - application/x-www-form-urlencoded
        - application/json
      produces:
        - application/json
      parameters:
        - name: email
          in: formData
          description: user's registered email address
          required: true
          type: string
        - name: password
          in: formData
          description: user's registered password
          required: true
          type: string
      responses:
        "200":
          description: successful operation
          schema:
            type: object
            items:
              $ref: "#/definitions/SuccessLoginResponse"
        "400":
          description: Bad request, missing some details.
          schema:
            type: object
            items:
              $ref: "#/definitions/BadRequestResponse"
        "401":
          description: Email or password is incorrect.
          schema:
            type: object
            items:
              $ref: "#/definitions/UnauthorizedResponse"
  "/api/v1/auth/register":
    post:
      tags:
        - user
      summary: Creates new user
      description: "Adds a new user into the application"
      operationId: userRegister
      consumes:
        - application/x-www-form-urlencoded
        - application/json
      produces:
        - application/json
      parameters:
        - name: firstname
          in: formData
          description: firstname of user
          required: true
          type: string
        - name: lastname
          in: formData
          description: lastname of user
          required: true
          type: string
        - name: phone
          in: formData
          description: phone number of user
          required: true
          type: integer
          format: int64
        - name: email
          in: formData
          description: email of user
          required: true
          type: string
        - name: password
          in: formData
          description: password of user
          required: true
          type: string
      responses:
        "201":
          description: successful operation
          schema:
            type: object
            items:
              $ref: "#/definitions/SuccessRegisterResponse"
        "400":
          description: Bad request, missing some details.
          schema:
            type: object
            items:
              $ref: "#/definitions/BadRequestResponse"
        "409":
          description: A user with this email already exists.
          schema:
            type: object
            items:
              $ref: "#/definitions/ConflictResponse"
        "422":
          description: Could not create user.
          schema:
            type: object
            items:
              $ref: "#/definitions/UnprocessableEntityResponse"
  /api/v1/auth/users:
    get:
      tags:
        - user
      summary: Get all users
      description: Get all the registered users
      operationId: fetchUser
      consumes:
        - application/json
        - application/x-www-form-urlencoded
      produces:
        - application/json
      responses:
        "200":
          description: successful operation
          schema:
            type: object
            items:
              $ref: "#/definitions/SuccessFetchUserResponse"
  /api/v1/stocks/company-profile:
    get:
      tags:
        - stock
      summary: Get stock company profile
      description: Get stock company profile
      operationId: fetchCompanyProfile
      consumes:
        - application/json
        - application/x-www-form-urlencoded
      produces:
        - application/json
      responses:
        "200":
          description: successful operation
          schema:
            type: object
            items:
              $ref: "#/definitions/SuccessStockResponse"
  /api/v1/stocks/market-news:
    get:
      tags:
        - stock
      summary: Get stock market news
      description: Get all stock market news
      operationId: fetchMarketNews
      consumes:
        - application/json
        - application/x-www-form-urlencoded
      produces:
        - application/json
      responses:
        "200":
          description: successful operation
          schema:
            type: object
            items:
              $ref: "#/definitions/SuccessStockResponse"
  /api/v1/stocks/company-news:
    get:
      tags:
        - stock
      summary: Get stock company news
      description: Get all stock company news
      operationId: fetchCompanyNews
      consumes:
        - application/json
        - application/x-www-form-urlencoded
      produces:
        - application/json
      responses:
        "200":
          description: successful operation
          schema:
            type: object
            items:
              $ref: "#/definitions/SuccessStockReponse"
  /api/v1/stocks/social-sentiment:
    get:
      tags:
        - stock
      summary: Get stock social sentiment
      description: Get all stock social sentiment
      operationId: fetchSocialSentiment
      consumes:
        - application/json
        - application/x-www-form-urlencoded
      produces:
        - application/json
      responses:
        "200":
          description: successful operation
          schema:
            type: object
            items:
              $ref: "#/definitions/SuccessStockResponse"
  /api/v1/stocks/peers:
    get:
      tags:
        - stock
      summary: Get all peers
      description: Get all the registered peers
      operationId: fetchPeers
      consumes:
        - application/json
        - application/x-www-form-urlencoded
      produces:
        - application/json
      responses:
        "200":
          description: successful operation
          schema:
            type: object
            items:
              $ref: "#/definitions/SuccessStockResponse"
  /api/v1/stocks/earning-surprises:
    get:
      tags:
        - stock
      summary: Get stock earning surprises
      description: Get all stock earning surprises
      operationId: fetchEarningSurprises
      consumes:
        - application/json
        - application/x-www-form-urlencoded
      produces:
        - application/json
      responses:
        "200":
          description: successful operation
          schema:
            type: object
            items:
              $ref: "#/definitions/SuccessStockResponse"
  /api/v1/stocks/recommendation-trends:
    get:
      tags:
        - stock
      summary: Get all recommendation trends
      description: Get all stock recommendation trends
      operationId: fetchRecommendationTrends
      consumes:
        - application/json
        - application/x-www-form-urlencoded
      produces:
        - application/json
      responses:
        "200":
          description: successful operation
          schema:
            type: object
            items:
              $ref: "#/definitions/SuccessStockResponse"
  /api/v1/stocks/stock-candle:
    get:
      tags:
        - stock
      summary: Get all stock candle
      description: Get all stock candle
      operationId: fetchStockCandle
      consumes:
        - application/json
        - application/x-www-form-urlencoded
      produces:
        - application/json
      responses:
        "200":
          description: successful operation
          schema:
            type: object
            items:
              $ref: "#/definitions/SuccessStockResponse"
  /api/v1/stocks/earning-calendar:
    get:
      tags:
        - stock
      summary: Get stock earning calendar
      description: Get all stock earning calendar
      operationId: fetchEarningCalendar
      consumes:
        - application/json
        - application/x-www-form-urlencoded
      produces:
        - application/json
      responses:
        "200":
          description: successful operation
          schema:
            type: object
            items:
              $ref: "#/definitions/SuccessStockResponse"
  /api/v1/stocks/quote:
    get:
      tags:
        - stock
      summary: Get all quote
      description: Get all stock quote
      operationId: fetchQuote
      consumes:
        - application/json
        - application/x-www-form-urlencoded
      produces:
        - application/json
      responses:
        "200":
          description: successful operation
          schema:
            type: object
            items:
              $ref: "#/definitions/SuccessStockResponse"
  /api/v1/profile/image/upload/{id}:
    put:
      tags:
        - user
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Numeric ID of the user to get
        - name: profileImage
          in: formData
          description: profile image of user
          required: true
          type: string
          format: binary
      summary: Add profile image
      description: Add a profile image for a user
      operationId: addProfileImage
      consumes:
        - multipart/form-data
      produces:
        - application/json
      responses:
        "200":
          description: successful operation
          schema:
            type: object
            items:
              $ref: "#/definitions/SuccessStockResponse"
  /api/v1/auth/users/{id}:
    get:
      tags:
        - user
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Numeric ID of the user to get
      summary: get user by id
      description: get a user's profile by id
      operationId: getUserbyId
      consumes:
        - application/json
        - application/x-www-form-urlencoded
      produces:
        - application/json
      responses:
        "200":
          description: successful operation
          schema:
            type: object
            items:
              $ref: "#/definitions/SuccessStockResponse"
  /api/v1/profile/edit/{id}:
    put:
      tags:
        - user
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Numeric ID of the user to get
        - name: firstname
          in: formData
          description: firstname of user
          type: string
        - name: lastname
          in: formData
          description: lastname of user
          type: string
        - name: phone
          in: formData
          description: phone number of user
          type: integer
          format: int64
        - name: isVerified
          in: formData
          description: email verification of user
          type: boolean
        - name: isSubscribed
          in: formData
          description: newsletter subscription of user
          type: boolean
        - name: isPushNotificationActive
          in: formData
          description: push notification preferrence of user
          type: boolean
        - name: isAdmin
          in: formData
          description: is user an admin
          type: boolean
        - name: isInvestor
          in: formData
          description: is user an investor
          type: boolean
      summary: Edit user profile 
      description: Edit user profile
      operationId: editProfile
      consumes:
        - application/json
        - application/x-www-form-urlencoded
      produces:
        - application/json
      responses:
        "200":
          description: successful operation
          schema:
            type: object
            items:
              $ref: "#/definitions/SuccessStockResponse"
  /api/v1/accounts:
    get:
      tags:
        - account
      summary: Get all accounts
      description: Get all user bank accounts
      operationId: getBankAccounts
      consumes:
        - application/json
        - application/x-www-form-urlencoded
      produces:
        - application/json
      responses:
        "200":
          description: successful operation
          schema:
            type: object
            items:
              $ref: "#/definitions/SuccessStockResponse"
  /api/v1/accounts/{id}:
    get:
      tags:
        - account
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Numeric ID of the user to get
      summary: Get a bank account
      description: Get a user bank account
      operationId: getBankAccountById
      consumes:
        - application/json
        - application/x-www-form-urlencoded
      produces:
        - application/json
      responses:
        "200":
          description: successful operation
          schema:
            type: object
            items:
              $ref: "#/definitions/SuccessStockResponse"
  /api/v1/accounts/add:
    post:
      tags:
        - account
      parameters:
        - name: bankname
          in: formData
          description: bank name of user
          type: string
        - name: userId
          in: formData
          description: id of user
          type: string
        - name: accountnumber
          in: formData
          description: account number of user
          type: integer
          format: int64
      summary: Add a bank account
      description: Add a user bank account
      operationId: addBankAccountById
      consumes:
        - application/json
        - application/x-www-form-urlencoded
      produces:
        - application/json
      responses:
        "201":
          description: successful operation
          schema:
            type: object
            items:
              $ref: "#/definitions/SuccessStockResponse"
definitions:
  User:
    title: User
    example:
      id: 14
      firstname: mike
      lastname: brown
      email: mikebrown@email.com
      phone: 18001119988
      role: not assigned
      isVerified: false
      isInvestor: false
      isSubscribed: false
      isPushNotificationActive: false
      isAdmin: false
      profileImage: alongurl.com
      account: 60d4e9020adaaa0004dc2ae5
    properties:
      id:
        type: integer
        format: int64
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
      password:
        type: string
      phone:
        type: integer
      role:
        type: string
        description: User's Role
        enum:
          - admin
          - investor
          - not assigned
      isVerified:
        type: boolen
      isInvestor:
        type: boolean
      isSubscribed:
        type: boolean
      isPushNotificationActive:
        type: boolean
      profileImage:
        type: string
      account:
        type: integer
    required:
      - id
      - firstname
      - lastname
      - email
      - phone
      - password
    xml:
      name: User
  Account:
    title: Account
    example:
      id: 14
      userId: 60d4e9020adaaa0004dc2ae5
      bankname: guaranteed trust bank
      accountnumber: 1201475986
    properties:
      id:
        type: integer
        format: int64
      userId:
        type: integer
        format: int64
      bankname:
        type: string
      accountnumber:
        type: integer
    required:
      - id
      - userId
      - bankname
      - accountnumber
    xml:
      name: Account
  SuccessRegisterResponse:
    title: SuccessRegisterResponse
    example:
      status: 201
      data:
        token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE0LCJlbWFpbCI6Im1pa2Vicm93bkBlbWFpbC5jb20iLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNTU4NDUzNzc3LCJleHAiOjE1NTg0NzUzNzd9.t8VZ-fJygbxNhrF3ADXlu4007n9WPP6ZEWlbjl96oS8
        user:
          id: 14
          firstname: fola
          lastname: fola
          email: fola@email.com
          phone: 18001119988
          role: not assigned
        message: User registration successful
    type: object
    properties:
      status:
        type: integer
        format: int32
      data:
        $ref: '#/definitions/RegisterData'
    required:
    - status
    - data
  RegisterData:
    title: RegisterData
    example:
      token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE0LCJlbWFpbCI6Im1pa2Vicm93bkBlbWFpbC5jb20iLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNTU4NDUzNzc3LCJleHAiOjE1NTg0NzUzNzd9.t8VZ-fJygbxNhrF3ADXlu4007n9WPP6ZEWlbjl96oS8
      user:
        id: 14
        firstname: fola
        lastname: fola
        email: fola@email.com
        phone: 18001119988
        role: not assigned
      message: User registration successful
    type: object
    properties:
      token:
        type: string
      user:
        $ref: '#/definitions/User'
      message:
        type: string
    required:
    - token
    - user
    - message
  SuccessLoginResponse:
    title: SuccessLoginResponse
    example:
      status: 200
      data:
        token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE0LCJlbWFpbCI6Im1pa2Vicm93bkBlbWFpbC5jb20iLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNTU4NDUzODc3LCJleHAiOjE1NTg0NzU0Nzd9.UHOEGRia69KZNS4G09UpYCTAiitw3hjYxDqPjVwZjEs
        user:
          id: 14
          firstname: fola
          lastname: fola
          email: fola@email.com
          phone: 18001119988
          role: not assigned
        message: User log in successful
    type: object
    properties:
      status:
        type: integer
        format: int32
      data:
        $ref: '#/definitions/LoginData'
    required:
    - status
    - data
  LoginData:
    title: LoginData
    example:
      token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE0LCJlbWFpbCI6Im1pa2Vicm93bkBlbWFpbC5jb20iLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNTU4NDUzNzc3LCJleHAiOjE1NTg0NzUzNzd9.t8VZ-fJygbxNhrF3ADXlu4007n9WPP6ZEWlbjl96oS8
      user:
        id: 14
        firstname: fola
        lastname: fola
        email: fola@email.com
        phone: 18001119988
        role: not assigned
      message: User log in successful
    type: object
    properties:
      token:
        type: string
      user:
        $ref: '#/definitions/User'
      message:
        type: string
    required:
    - token
    - user
    - message
  SuccessFetchUserResponse:
    title: SuccessFetchUserResponse
    example:
      status: 200
      data:
        id: 14
        firstname: mike
        lastname: brown
        email: mikebrown@email.com
        phone: 18001119988
        status: verified
        registered: 2019-05-21T00:00:00Z
    type: object
    properties:
      status:
        type: integer
        format: int32
      data:
        $ref: '#/definitions/FetchUserData'
    required:
    - status
    - data
  FetchUserData:
    title: FetchUserData
    example:
      message: Users fetched successfully
      count: 109
      users:
        $ref: '#/definitions/Users'
    type: object
    properties:
      message:
        type: string
      count:
        type: integer
      users:
        type: array
        $ref: '#/definitions/Users'
    required:
    - message
    - count
    - users
  Users:
    title: Users
    properties:
      users:
        type: array
        user:
          type: object
          properties:
            id:
              type: integer
            firstName:
              type: string
            lastName:
              type: string
            email:
              type: string
            password:
              type: string
            phone:
              type: string
            role:
              type: string
              description: User's Role
              enum:
                - admin
                - investor
                - not assigned
    required:
      - users
    xml:
      name: Users
  BadRequestResponse:
    title: BadRequestResponse
    example:
      status: 400
      error: Bad request, missing some details.
    type: object
    properties:
      status:
        type: integer
        format: int32
      error:
        type: string
    required:
    - status
    - error
  ConflictResponse:
    title: ConflictResponse
    example:
      status: 409
      error: A user with this email already exists.
    type: object
    properties:
      status:
        type: integer
        format: int32
      error:
        type: string
    required:
    - status
    - error
  UnprocessableEntityResponse:
    title: UnprocessableEntityResponse
    example:
      status: 422
      error: Could not create user.
    type: object
    properties:
      status:
        type: integer
        format: int32
      error:
        type: string
    required:
    - status
    - error
  UnauthorizedResponse:
    title: UnauthorizedResponse
    example:
      status: 401
      error: Could not create user.
    type: object
    properties:
      status:
        type: integer
        format: int32
      error:
        type: string
    required:
    - status
    - error
  SuccessStockResponse:
    title: SuccessStockResponse
    example:
      status: 200
      data:
        id: 11
        firstname: mike
        lastname: brown
        email: mikebrown@email.com
        amount: 100000
        tenor: 6
        status: pending
        paymentinstallment: 17156.139999999999
        balance: 102936.84
        interest: 2936.8400000000001
        createdon: 2019-05-21T00:00:00Z
    type: object
    properties:
      status:
        type: integer
        format: int32
      data:
        $ref: '#/definitions/StockData'
    required:
    - status
    - data
  StockData:
    title: StockData
    example:
      status: 200
      data:
        some: data
        key: pair
    type: object
    properties:
      status:
        type: integer
      data:
        type: object
    required:
    - status
    - data